## Disable default rules
disabled_rules:
  - inclusive_language
  - function_parameter_count
  - closure_parameter_position
  - type_body_length
  - todo

## Enable disabled rules
opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - discouraged_object_literal
  - empty_count
  - empty_collection_literal
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - single_test_class
  - sorted_first_last
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

## Length configurations
line_length: 120

identifier_name:
  min_length:
    warning: 3
  max_length:
    warning: 40
  excluded:
    - id
    - ok

file_length:
  warning: 500

closure_body_length:
  warning: 50

function_body_length:
  warning: 50

force_cast: warning
force_try: warning

nesting:
  type_level:
    warning: 2

warning_threshold: 1

excluded:
    - Resources/R.generated.swift
